# Generated by Django 3.1.3 on 2020-11-29 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='created',
            new_name='created_at',
        ),
    ]
